expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2
ignore_repeated_errors = On

allow_url_fopen = On
allow_url_include = Off

file_uploads = On
upload_max_filesize = 64M
post_max_size = 64M
max_file_uploads = 20

max_execution_time = 0
max_input_time = 60
memory_limit = 512M
max_input_vars = 2000
default_charset = UTF-8

session.use_strict_mode = 1
session.use_only_cookies = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax

disable_functions = passthru,show_source,dl
disable_classes =

zend.exception_ignore_args = On
zend.enable_gc = On

realpath_cache_size = 4096K
realpath_cache_ttl = 600
