[www]
user = www-data
group = www-data
listen = 9000

pm = dynamic
pm.max_children = 8
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 2
pm.max_requests = 500
pm.status_path = /fpm-status

ping.path = /ping
ping.response = pong

clear_env = no
catch_workers_output = yes
decorate_workers_output = no
security.limit_extensions = .php

request_terminate_timeout = 60
request_slowlog_timeout = 10s
slowlog = /proc/self/fd/2
